before_install:
 - sudo apt-get -qq update
 - sudo apt-get install -y libapr1 openssl
 - gem install bundler
language: ruby
rvm:
  - "1.9.3"
  - "2.0.0"
  - "2.1.0"
  - "2.1.1"
  - "2.1.2"
  - "2.1.4"
  - "2.2.0"  
  - "2.3.1"
